apiVersion: v1

kind: Pod

metadata:

  name: flaskapp-pod

  labels:

    app: flaskapp

spec:

  containers:

  - name: flaskapp-container

    image: uuuks/flaskapp:latest

    ports:

    - containerPort: 5000

  imagePullSecrets:

  - name: myregistrykey


